version: '3.3'
services:
  client:
    build: 
      context: ./client
    ports:
      - 8080:80
  mongodb:
    image: mongo:4
    volumes:
      - mongo_db:/data/db
  server:
    build:
      context: ./server
    ports:
      - 8081:8081
volumes:
  mongo_db:
