version: '3.3'
services:
  client:
    image: messer/client
    ports:
      - 8080:80
  mongodb:
    image: mongo:4
    volumes:
      - mongo_db:/data/db
  server:
    image: messer/server
    ports:
      - 8081:8081
volumes:
  mongo_db:
